### ISSUE TITLE
thank you button popup form

### ISSUE THREAD

**Issue by corinatheguru** [mavericksthinker/charlanderson#1]
the popup for after entering my info and hitting submit returns an error message, see attached image. The day that the website went live this issue has been there, not sure why the form is not working, not able to receive the download.
<img width="1558" alt="Screen Shot 2020-10-29 at 4 57 00 PM" src="https://user-images.githubusercontent.com/73307739/97641212-fa380280-1a07-11eb-85ef-888abfc45ead.png">

**Comment by mavericksthinker** [comment]
Hello Corina,
I had it tested when the code was deployed on the server and it was working
as expected. If there is error in form submission, then it can be
1. If the identifier of the form has been changed.
2. The gmail SMTP configuration has passed its limitation for sending free
emails or there is configuration problem.

Measures to be taken :
1. Make sure that the id of the form matches the javascript event handler
that triggers the download.
2. Reconfigure SMTP ( [access key and secret]/ [ email configuration] )

If the issue still persists, let me know and I will fix it.
In the meantime I will also try to find time to look into it as well. But
currently the smtp is running under my free account, better to transfer it
to the one belonging to Charla for more accessibility.

Responding to the question in the other email,
To deploy code to the server :
First clone the repository and make changes in a new branch.
Push the branch from local computer to remote using appropriate git command
and merge it to master branch.( Doing this will keep a record of all the
changes that has been done to the website and if any breaking changes has
been accidentally implemented then its easier to revert the code ).
Then ssh to the server ( if you dont have access, then contact Charla as
she is the admin ).
Then git pull the master branch in
apps/wordpress/htdocs/wp-contents/themes/abwebsolutions directory.

If you need further help then please let me know.

It's better to communicate via Microsoft Teams as it will be faster to
address the issues. I will invite you to the official team.

Regards,
Mavericks.

**Comment by corinatheguru** [comment]
Hi Aileen, 

 

Can you please add me to MS Teams under this new email – theguru@thegurubehindtheguru.com the other is no longer being used and we checked it the other day and it was misspelled.

 

 

Be courageous,

 

Corina L.

 

The Guru Behind The Guru

thegurubehindtheguru@gmail.com

www.thegurubehindtheguru.com

https://www.linkedin.com/in/corinalozano/
